name: shop_market
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  zoom_tap_animation: ^1.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
